apiVersion: apps/v1
kind: Deployment
metadata:
  name: icav-assign5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icav-assign5
  template:
    metadata:
      labels:
        app: icav-assign5
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: icav-assign5
        image: testreganji.azurecr.io/testreganji:latest
        imagePullPolicy: Never
